/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check service health and readiness */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current dashboard summary */
        get: operations["getDashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/networks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List networks visible to the authenticated user */
        get: operations["listNetworks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/networks/{networkId}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get historical activity for a network */
        get: operations["getNetworkActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sensors and their latest status */
        get: operations["listSensors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sensors/{sensorId}/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get historical numeric readings for a sensor */
        get: operations["getSensorReadings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sensors/{sensorId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get historical discrete events for a sensor */
        get: operations["getSensorEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/realtime/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream live updates using Server-Sent Events
         * @description Opens a long-lived SSE connection for the selected network.
         *
         *     The server emits named events: `sensor.reading`, `sensor.event`,
         *     `activity.updated`, and `heartbeat`. Each `data` field is a JSON-encoded
         *     object described by the corresponding realtime schema.
         *
         *     The server sends an `id` with data events. Native `EventSource`
         *     automatically reconnects and sends the most recent ID in the
         *     `Last-Event-ID` header, allowing the backend to replay a small missed-event
         *     buffer. Heartbeats should be sent periodically so intermediaries do not
         *     close an otherwise idle connection.
         *
         *     Native browser `EventSource` cannot set an `Authorization` header, so the
         *     frontend consumes this stream with an authenticated fetch-based SSE client.
         *     The client is responsible for reconnecting with the latest access token and
         *     `Last-Event-ID`. Do not put a long-lived OAuth access token in the query
         *     string.
         */
        get: operations["streamRealtimeEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "degraded";
            dependencies: {
                database: components["schemas"]["DependencyStatus"];
                mqtt: components["schemas"]["DependencyStatus"];
            };
        };
        /** @enum {string} */
        DependencyStatus: "connected" | "disconnected";
        User: {
            id: string;
            /** Format: email */
            email?: string | null;
            displayName?: string | null;
            roles: string[];
        };
        Network: {
            id: number;
            /** @example Home WiFi Motion Network */
            name: string;
        };
        Sensor: {
            /** @example SENSOR_7C3E822F6E550000 */
            id: string;
            networkId: number;
            /** @example Bathroom */
            location: string;
            capabilities: components["schemas"]["SensorCapability"][];
            status: components["schemas"]["SensorStatus"];
            /** Format: date-time */
            lastSeenAt?: string | null;
            latestReadings?: components["schemas"]["Reading"][];
        };
        /** @enum {string} */
        SensorCapability: "temperature" | "humidity" | "vibration";
        /** @enum {string} */
        SensorStatus: "online" | "offline" | "unknown";
        SensorList: {
            data: components["schemas"]["Sensor"][];
        };
        /** @enum {string} */
        Metric: "temperature" | "humidity";
        Reading: {
            id: string;
            sensorId: string;
            metric: components["schemas"]["Metric"];
            value: number;
            /** @example C */
            unit: string;
            /** Format: date-time */
            timestamp: string;
        };
        SensorEvent: {
            id: string;
            sensorId: string;
            type: components["schemas"]["SensorEventType"];
            /** Format: date-time */
            timestamp: string;
        };
        /** @enum {string} */
        SensorEventType: "detected";
        ActivityPoint: {
            networkId: number;
            /** @description Fraction of the time bucket in which motion was detected. */
            activity: number;
            /** Format: date-time */
            timestamp: string;
        };
        MetricSummary: {
            metric: components["schemas"]["Metric"];
            current: number;
            unit: string;
            average: number;
            minimum: number;
            maximum: number;
            /** Format: date-time */
            updatedAt: string;
        };
        DashboardSummary: {
            networkId: number;
            range: components["schemas"]["TimeRange"];
            metrics: components["schemas"]["MetricSummary"][];
            door: {
                /** Format: date-time */
                lastDetectedAt?: string | null;
                eventCount: number;
            };
            activity: {
                current: number;
                average: number;
                peak: number;
            };
        };
        ReadingPage: components["schemas"]["PageMetadata"] & {
            data: components["schemas"]["Reading"][];
        };
        SensorEventPage: components["schemas"]["PageMetadata"] & {
            data: components["schemas"]["SensorEvent"][];
        };
        ActivityPage: components["schemas"]["PageMetadata"] & {
            data: components["schemas"]["ActivityPoint"][];
        };
        PageMetadata: {
            nextCursor: string | null;
        };
        RealtimeEventBase: {
            /** @description Monotonically sortable event identifier used for SSE resume. */
            id: string;
            type: string;
            /** Format: date-time */
            occurredAt: string;
        };
        SensorReadingRealtimeEvent: components["schemas"]["RealtimeEventBase"] & {
            /** @constant */
            type?: "sensor.reading";
            data: components["schemas"]["Reading"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sensor.reading";
        };
        SensorEventRealtimeEvent: components["schemas"]["RealtimeEventBase"] & {
            /** @constant */
            type?: "sensor.event";
            data: components["schemas"]["SensorEvent"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sensor.event";
        };
        ActivityRealtimeEvent: components["schemas"]["RealtimeEventBase"] & {
            /** @constant */
            type?: "activity.updated";
            data: components["schemas"]["ActivityPoint"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "activity.updated";
        };
        HeartbeatRealtimeEvent: components["schemas"]["RealtimeEventBase"] & {
            /** @constant */
            type?: "heartbeat";
            data: Record<string, never>;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "heartbeat";
        };
        RealtimeEvent: components["schemas"]["SensorReadingRealtimeEvent"] | components["schemas"]["SensorEventRealtimeEvent"] | components["schemas"]["ActivityRealtimeEvent"] | components["schemas"]["HeartbeatRealtimeEvent"];
        /** @enum {string} */
        Interval: "raw" | "1m" | "5m" | "15m" | "1h" | "1d";
        /** @enum {string} */
        TimeRange: "1h" | "6h" | "24h" | "7d" | "30d";
        ApiError: {
            code: string;
            message: string;
            requestId: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Request parameters are invalid. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "INVALID_QUERY_PARAMETER",
                 *       "message": "The `from` timestamp must be earlier than `to`.",
                 *       "requestId": "2f1d0c26-9644-4f9f-a770-41c1e8bdb5f8"
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description A valid access token or authenticated session is required. */
        Unauthorized: {
            headers: {
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UNAUTHORIZED",
                 *       "message": "A valid OAuth access token is required.",
                 *       "requestId": "2f1d0c26-9644-4f9f-a770-41c1e8bdb5f8"
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description The authenticated user cannot access this resource. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "FORBIDDEN",
                 *       "message": "You do not have access to this resource.",
                 *       "requestId": "2f1d0c26-9644-4f9f-a770-41c1e8bdb5f8"
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description The requested resource was not found or is not visible to the user. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOT_FOUND",
                 *       "message": "The requested resource was not found.",
                 *       "requestId": "2f1d0c26-9644-4f9f-a770-41c1e8bdb5f8"
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description The client has opened too many requests or realtime connections. */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "TOO_MANY_REQUESTS",
                 *       "message": "Too many realtime connections.",
                 *       "requestId": "2f1d0c26-9644-4f9f-a770-41c1e8bdb5f8"
                 *     }
                 */
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        NetworkIdPath: number;
        NetworkIdQuery: number;
        /** @example SENSOR_7C3E822F6E550000 */
        SensorIdPath: string;
        /** @description Inclusive range start. Defaults to 24 hours before `to`. */
        From: string;
        /** @description Exclusive range end. Defaults to the current time. */
        To: string;
        Limit: number;
        /** @description Opaque continuation cursor returned by the previous request. */
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is ready to accept traffic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description The process is running, but one or more dependencies are unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "degraded",
                     *       "dependencies": {
                     *         "database": "disconnected",
                     *         "mqtt": "connected"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The identity derived from the validated access token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDashboardSummary: {
        parameters: {
            query: {
                networkId: components["parameters"]["NetworkIdQuery"];
                /** @description Time range used to calculate summary statistics. */
                range?: components["schemas"]["TimeRange"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current readings and statistics for the selected network. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listNetworks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available IoT networks. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Network"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getNetworkActivity: {
        parameters: {
            query?: {
                /** @description Inclusive range start. Defaults to 24 hours before `to`. */
                from?: components["parameters"]["From"];
                /** @description Exclusive range end. Defaults to the current time. */
                to?: components["parameters"]["To"];
                /** @description Bucket size. Use `raw` to return stored 15-minute buckets unchanged. */
                interval?: components["schemas"]["Interval"];
                limit?: components["parameters"]["Limit"];
                /** @description Opaque continuation cursor returned by the previous request. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                networkId: components["parameters"]["NetworkIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity time-series points in ascending timestamp order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listSensors: {
        parameters: {
            query: {
                networkId: components["parameters"]["NetworkIdQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sensors belonging to the selected network. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getSensorReadings: {
        parameters: {
            query: {
                metric: components["schemas"]["Metric"];
                /** @description Inclusive range start. Defaults to 24 hours before `to`. */
                from?: components["parameters"]["From"];
                /** @description Exclusive range end. Defaults to the current time. */
                to?: components["parameters"]["To"];
                /** @description Aggregation interval. Use `raw` for unaggregated readings. */
                interval?: components["schemas"]["Interval"];
                limit?: components["parameters"]["Limit"];
                /** @description Opaque continuation cursor returned by the previous request. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                /** @example SENSOR_7C3E822F6E550000 */
                sensorId: components["parameters"]["SensorIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Numeric readings in ascending timestamp order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getSensorEvents: {
        parameters: {
            query?: {
                /** @description Optionally filter by event type. */
                type?: components["schemas"]["SensorEventType"];
                /** @description Inclusive range start. Defaults to 24 hours before `to`. */
                from?: components["parameters"]["From"];
                /** @description Exclusive range end. Defaults to the current time. */
                to?: components["parameters"]["To"];
                limit?: components["parameters"]["Limit"];
                /** @description Opaque continuation cursor returned by the previous request. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                /** @example SENSOR_7C3E822F6E550000 */
                sensorId: components["parameters"]["SensorIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discrete sensor events in descending timestamp order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorEventPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    streamRealtimeEvents: {
        parameters: {
            query: {
                networkId: components["parameters"]["NetworkIdQuery"];
            };
            header?: {
                /** @description ID of the last event processed by the client before reconnecting. */
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description A continuous `text/event-stream`. This response remains open until the
             *     client disconnects or the server terminates it.
             */
            200: {
                headers: {
                    /** @description SSE responses must not be cached. */
                    "Cache-Control"?: string;
                    /** @description Disables proxy buffering when supported. */
                    "X-Accel-Buffering"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example id: 01J4Z6Y7YVW8G3PGFQW7RBM6NB
                     *     event: sensor.reading
                     *     data: {"type":"sensor.reading","occurredAt":"2026-08-06T12:00:10Z","data":{"id":"reading-123","sensorId":"SENSOR_7C3E822F6E550000","metric":"temperature","value":24.6,"unit":"C","timestamp":"2026-08-06T12:00:10Z"}}
                     */
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
}
